name: Test
"on":
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
    test:
        name: 'Test: ${{matrix.os}}'
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: true
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v3
            - name: install deno
              uses: denoland/setup-deno@v1
              with:
                deno-version: v1.x
            - name: run test
              run: deno test -A --unstable ./mod.test.ts